version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"    # RabbitMQ default port
      - "15672:15672"  # RabbitMQ Management UI

  user_service:
    build: ./user_service
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - "8001:8001"

  task_service:
    build: ./task_service
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - "8002:8002"

  notification_service:
    build: ./notification_service
    depends_on:
      - rabbitmq
    ports:
      - "8003:8003"
